#Sever port settings
server:
  port: 1111

#Spring boot specific settings
spring:
  profiles:
    active: dev
  main:
    banner-mode: 'OFF'

# Default logging framework: LOGBACK
logging:
  level:
#    com.*: 'OFF'
#    org.*: 'OFF'
    org.springframework.web: ERROR
#    springfox.*: 'OFF'